[versions]
androidGradlePlugin = "8.0.2"
androidLibrary = "8.0.2"
kotlinAndroid = "1.9.0"
kotlinJvm = "1.9.0"
androidxComposeCompiler = "1.5.0"
jvmTarget = "18"

coreKtx = "1.10.1"
splashScreen = "1.0.1"
activityCompose = "1.7.2"
composeNavigation = "2.6.0"
composeBOM = "2023.06.01"
kotlinBOM = "1.9.0"
androidXLifecycle = "2.6.1"
androidMaterial3 = "1.1.1"

junit = "4.13.2"
junitExtension = "1.1.5"
espressoCore = "3.5.1"


[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidXLifecycle" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBOM" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBOM" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidMaterial3" }

test-junit = { module = "junit:junit", version.ref = "junit" }
test-junitExtension = { module = "androidx.test.ext:junit", version.ref = "junitExtension" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
test-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBOM" }
test-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeBOM" }
test-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }


[bundles]
androidx-compose-bom = ["compose-bom", "ui-tooling", "compose-ui", "compose-ui-graphics", "compose-tooling-preview", "androidx-material3"]


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
java-library = { id = "java-library" }